name: Build and Push Docker Image to Docker Hub

on:
  push:
    # --- 核心修改 START ---
    # 监听所有我们关心的分支
    branches: [ "main", "rollback-test", "final-rollback-test" ] 
    # --- 核心修改 END ---
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 动态检查 Dockerfile 的正确路径
      - name: Check Dockerfile path
        id: check_dockerfile
        run: |
          if [ -f docker/Dockerfile ]; then
            echo "path=docker/Dockerfile" >> $GITHUB_OUTPUT
          else
            echo "path=Dockerfile" >> $GITHUB_OUTPUT
          fi

      # 3. 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. 构建并推送，使用动态路径和动态标签
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ steps.check_dockerfile.outputs.path }} 
          push: true
          # --- 核心修改 START ---
          # 增加对 final-rollback-test 分支的标签逻辑
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/aistudio-proxy:${{
              github.ref_name == 'main' && 'latest' ||
              github.ref_name == 'rollback-test' && 'rollback' ||
              github.ref_name == 'final-rollback-test' && 'rollback-final' ||
              'dev'
            }}
          # --- 核心修改 END ---