# 工作流名称
name: Build and Push Docker Image to Docker Hub

# 触发条件：当有代码推送到 main 分支时，或手动触发时
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# 任务
jobs:
  build-and-push:
    # 运行环境
    runs-on: ubuntu-latest

    # 步骤
    steps:
      # 1. 检出代码：将仓库代码下载到运行环境中
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 登录 Docker Hub：使用我们之前设置的机密信息
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. 构建并推送 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # 使用当前目录作为构建上下文
          push: true  # 确认推送
          # 自动为镜像打标签，格式为 "你的DockerHub用户名/仓库名:latest"
          # ${{ github.repository }} 会自动变成 "你的GitHub用户名/AIstudioProxyAPI"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/aistudio-proxy:latest 